imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: [es] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    serializer: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    spool:     { type: memory }

guzzle:
    clients:
        api_vault:
            base_url: "%service_vault_url%"
        api_despegar:
            base_url: "%service_url%"
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    temporary_folder: %kernel.cache_dir%/../web/uploads

lexik_currency:
    currencies:
        default: ARS              # [required] the default currency
        managed: [ARS, USD]  # [required] all currencies used in your app
    decimal_part:
        precision:  0                           # number of digits for the decimal part
#        round_mode: down                          # round mode to use (up|down|even|odd)
    default_adapter: doctrine_currency_adapter

#FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: VientoSur\App\AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template:   email/password_resetting.email.twig
            from_email:
                address:        info@vientosur.net
                sender_name:    info@vientosur.net
    registration:
        form:
            type: BackendBundle\Form\RegisterType
        confirmation:
            enabled: true
            from_email:
                address:        info@vientosur.net
                sender_name:    Registro de usuario
    resetting:
        email:
            from_email:
                address:        info@vientosur.net
                sender_name:    VS - Resetting account


#Stof Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            loggable: true
            softdeleteable: true
            translatable: true

# Vich Configuration
vich_uploader:
    db_driver: orm
    mappings:
        image_promotion:
            uri_prefix:         /uploads/promotions/image
            upload_destination: '%kernel.root_dir%/../web/uploads/promotions/image'
            namer:
                service: vich_uploader.namer_uniqid 
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false
        image_activiti_agency:
            uri_prefix:         /uploads/activiti_agency/image
            upload_destination: '%kernel.root_dir%/../web/uploads/activiti_agency/image'
            namer:
                service: vich_uploader.namer_uniqid 
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false    
        file_activiti_agency:
            uri_prefix:         /uploads/activiti_agency/file
            upload_destination: '%kernel.root_dir%/../web/uploads/activiti_agency/file'
            namer:
                service: vich_uploader.namer_uniqid 
            inject_on_load:     false
            delete_on_update:   false
            delete_on_remove:   false     
#        gallery_image:
#            uri_prefix:         /uploads/gallery
#            upload_destination: '%kernel.root_dir%/../web/uploads/gallery'
#            inject_on_load:     false
#            delete_on_update:   false
#            delete_on_remove:   false

#FOSRest Configuration
fos_rest:
    routing_loader:
        default_format: json
        include_format: false

#NelmioApiDoc Configuratio
nelmio_api_doc:
    name: Viento Sur Api

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: true
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
            max_age: 3600

#KnpPagintator Config
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:foundation_v5_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

#foselastica config
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                reservation:
                    properties:
                        hotelId: ~
                        reservationId: ~
                        totalPrice: ~
                        holderName: ~
                        checkin: ~
                        checkout: ~
                        origin: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\Reservation
                        provider: ~
                        finder: ~
                hotel:
                    properties:
                        name: ~
                        description: ~
                        address: ~
                        stars: ~
                        origen: ~
                        latitude: ~
                        longitude: ~
                        percentageGain: ~
                        hotelTypes: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\Hotel
                        provider: ~
                        finder: ~
                room:
                    properties:
                        name: ~
                        roomCode: ~
                        availability: ~
                        capacity: ~
                        nightlyPrice: ~
                        cancellationPolicity: ~
                        paymentType: ~
                        mealPlan: ~
                        hotel: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\Room
                        provider: ~
                        finder: ~
                bed:
                    properties:
                        name: ~
                        quantity: ~
                        room: ~
                        bedType: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\Bed
                        provider: ~
                        finder: ~
                promotionSections:
                    properties:
                        title: ~
                        subtitle: ~
                        status: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\PromotionSections
                        provider: ~
                        finder: ~
                promotion:
                    properties:
                        name: ~
                        description: ~
                        link: ~
                        section: ~
                        status: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\Promotions
                        provider: ~
                        finder: ~
                hotel:
                    properties:
                        name: ~
                        address: ~
                        hotelTypes: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: VientoSur\App\AppBundle\Entity\Hotel
                        provider: ~
                        finder: ~